models/News.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property string $title
 * @property string $createdAt
 * @property string|null $updatedAt
 * @property int $categoryId
 *
 * @property NewsComment[] $newsComments
 */
class News extends \yii\db\ActiveRecord
{
	/**
	 * {@inheritdoc}
	 */
	public static function tableName()
	{
		return 'news';
	}

	/**
	 * {@inheritdoc}
	 */
	public function rules()
	{
		return [
			[['title', 'createdAt'], 'required'],
			[['createdAt', 'updatedAt'], 'safe'],
			[['title'], 'string', 'max' => 128],
		];
	}

	/**
	 * {@inheritdoc}
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'title' => 'Title',
			'createdAt' => 'Created At',
			'updatedAt' => 'Updated At',
		];
	}

	/**
	 * Gets query for [[NewsComments]].
	 *
	 * @return \yii\db\ActiveQuery
	 */
	public function getNewsComments()
	{
		return $this->hasMany(NewsComment::className(), ['newsId' => 'id']);
	}
}

controllers/NewsController.php
<?php

namespace app\controllers;

use app\models\News;
use app\models\NewsComment;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class NewsController extends Controller
{
	public function actionIndex($categoryId)
	{
		$news = News::find()
			->where(['categoryId' => $categoryId])
			->orderBy(['createdAt' => SORT_DESC])
			->all();

		return $this->render('index', [
			'news' => $news
		]);
	}

	public function actionView($id)
	{
		$model = News::findOne($id);
		$comments = NewsComment::find()
			->where(['newsId' => $id])
			->all();

		if ($model === null) {
			throw new NotFoundHttpException('Новость не найдена.');
		}

		return $this->render('view', [
			'model' => $model,
			'comments' => $comments
		]);
	}
}

views/news/index.php
<?php

use yii\helpers\Html;

/* @var $news \app\models\News[] */

?>

<?php foreach ($news as $item): ?>

<article>
	<h1><?= Html::a($item->title, ['news/view', 'id' => $item->id]) ?></h1>
</article>

<?php endforeach; ?>

views/news/view.php
<?php

/* @var $model \app\models\News */
/* @var $comments \app\models\NewsComment[] */

?>

<article>
	<h1><?= $model->title ?></h1>
	<p><?= $model->id ?></p>
	<ul>
		<?php foreach ($comments as $comment): ?>
			<li>
				<?= $comment->text ?>
				<time class="small text-muted"><?= date('d.m.Y H:i:s', strtotime($comment->createdAt)) ?></time>
			</li>
		<?php endforeach; ?>
	</ul>
</article>